services:
  backend:
    build: ./apps/api
    container_name: dronefood-backend
    env_file:
      - ./apps/api/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  user:
    build:
      context: .
      dockerfile: apps/customer-web/Dockerfile
    container_name: dronefood-user
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

  admin:
    build:
      context: .
      dockerfile: apps/admin-web/Dockerfile
    container_name: dronefood-admin
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped

  restaurant:
    build:
      context: .
      dockerfile: apps/restaurant-web/Dockerfile
    container_name: dronefood-restaurant
    ports:
      - "5175:80"
    depends_on:
      - backend
    restart: unless-stopped
